version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: crud_user
#      MYSQL_USER: root
#      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"

  springbootapp:
    image: crud_user:latest
    container_name: crud_user-container
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/crud_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
